digit:
  length_0: 0
  length_2: 2
  length_6: 6
  length_10: 10
  length_30: 30
  length_100: 100
  length_255: 255
pagination:
  per_page_10: 10
h_m_s_format: "%Y-%m-%d %H:%M %p"
chart_width_500: "400px"
chart_height_600: "350px"
